"""your message

Revision ID: 2627a31b947d
Revises: 9bf7eb73be9e
Create Date: 2024-04-11 23:42:19.416440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2627a31b947d'
down_revision = '9bf7eb73be9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
