"""your message

Revision ID: 505db6649aa8
Revises: 8b45f0d5ee0c
Create Date: 2024-04-11 23:45:07.002630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505db6649aa8'
down_revision = '8b45f0d5ee0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('body', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'body')
    # ### end Alembic commands ###
