"""your message

Revision ID: 8b45f0d5ee0c
Revises: 2627a31b947d
Create Date: 2024-04-11 23:43:55.061816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b45f0d5ee0c'
down_revision = '2627a31b947d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
